version: '3.8'

services:
   nodejs:
      container_name: nodejs
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3001:3001'
      volumes:
         - .:/app
      depends_on:
         - mongodb
         - redis
      env_file:
         - .env

   mongodb:
      container_name: mongodb
      image: mongo:latest
      ports:
         - '27017:27017'
      volumes:
         - ./data/mongodb:/data/db

   redis:
      container_name: redis
      image: redis:latest
      ports:
         - '6379:6379'
      volumes:
         - ./data/redis:/data
