services:
   user-token:
      build:
         context: .
         dockerfile: ./apps/user-token/dockerfile
         target: development
      command: npm run start:dev user-token
      env_file:
         - ./apps/user-token/.env
      depends_on:
         - mongodb-primary
         - mongodb-secondary
         - mongodb-arbiter
         # - billing
         - auth
         # - rabbitmq
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
      ports:
         - '3001:3001'
   auth:
      build:
         context: .
         dockerfile: ./apps/auth/dockerfile
         target: development
      command: npm run start:dev auth
      ports:
         - '3001:3001'
      env_file:
         - ./apps/auth/.env
      depends_on:
         - mongodb-primary
         - mongodb-secondary
         - mongodb-arbiter
         # - rabbitmq
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules

   mongodb-primary:
      image: docker.io/bitnami/mongodb:7.0
      environment:
         - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
         - MONGODB_REPLICA_SET_MODE=primary
         - MONGODB_ROOT_PASSWORD=password123
         - MONGODB_REPLICA_SET_KEY=replicasetkey123
      volumes:
         - 'mongodb_master_data:/bitnami/mongodb'
      ports:
         - '27017:27017'

   mongodb-secondary:
      image: docker.io/bitnami/mongodb:7.0
      depends_on:
         - mongodb-primary
      environment:
         - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
         - MONGODB_REPLICA_SET_MODE=secondary
         - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
         - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
         - MONGODB_REPLICA_SET_KEY=replicasetkey123

   mongodb-arbiter:
      image: docker.io/bitnami/mongodb:7.0
      depends_on:
         - mongodb-primary
      environment:
         - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
         - MONGODB_REPLICA_SET_MODE=arbiter
         - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
         - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
         - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
   mongodb_master_data:
      driver: local
